version: '3.8'
services:
  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - '8888:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

